h24:
	convert original/toggle_off.png -resize x24 24/toggle_off_24.png
	convert original/toggle_on.png -resize x24 24/toggle_on_24.png

h48:
	convert original/toggle_off.png -resize x48 48/toggle_off_48.png
	convert original/toggle_on.png -resize x48 48/toggle_on_48.png
